[build]
  publish = "."
  command = ""

  [build.environment]
    NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Route all /api/* to the proxy function (supports /api/rents, /api/overrides, etc.)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/air-proxy/:splat"
  status = 200
  force = true
