[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  node_js_version = "20"

# Route all /api/* requests to the proxy function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/air-proxy/:splat"
  status = 200
  force = true